const wordsData = {
  abate: {
    type: "verb",
    meaning: "To become less intense or widespread.",
    trick: "Think of 'rebate' - to abate is to reduce or lessen.",
    synonyms: ["diminish", "decrease", "lessen", "reduce"],
    examples: [
      "The storm suddenly abated.",
      "They waited for the crowd's excitement to abate.",
      "The government is taking measures to abate pollution.",
      "His anger began to abate after a few minutes.",
      "The pain in her shoulder finally abated.",
    ],
  },
  aberrant: {
    type: "adjective",
    meaning: "Departing from an accepted standard.",
    trick: "Think of 'a bear ant' - an ant that behaves like a bear is aberrant.",
    synonyms: ["abnormal", "atypical", "anomalous", "deviant"],
    examples: [
      "His aberrant behavior raised eyebrows.",
      "The experiment's results were aberrant.",
      "She was punished for her aberrant actions.",
      "Aberrant weather patterns are becoming more common.",
      "The disease caused aberrant cell growth.",
    ],
  },
  abhor: {
    type: "verb",
    meaning: "To regard with disgust and hatred.",
    trick: "Think of 'a bore' - you abhor something that is a bore.",
    synonyms: ["detest", "hate", "loathe", "despise"],
    examples: [
      "She abhors cruelty to animals.",
      "He abhorred the idea of being idle.",
      "The community abhors violence.",
      "They abhorred the dictator's oppressive regime.",
      "She abhors dishonesty in all forms.",
    ],
  },
  abjure: {
    type: "verb",
    meaning: "To solemnly renounce a belief, cause, or claim.",
    trick: "Think of 'jury' - you abjure something formally like in front of a jury.",
    synonyms: ["renounce", "relinquish", "reject", "forswear"],
    examples: [
      "He abjured his allegiance to the king.",
      "She abjured her old beliefs.",
      "The politician abjured his former position.",
      "He abjured his claim to the throne.",
      "They abjured their support for the controversial policy.",
    ],
  },
  abrogate: {
    type: "verb",
    meaning: "To repeal or do away with a law, right, or formal agreement.",
    trick: "Think of 'a broken gate' - to abrogate is to break away or repeal.",
    synonyms: ["repeal", "revoke", "rescind", "annul"],
    examples: [
      "The government abrogated the outdated law.",
      "They voted to abrogate the treaty.",
      "The contract was abrogated by mutual consent.",
      "The decision to abrogate the agreement was controversial.",
      "He abrogated his responsibilities.",
    ],
  },
  abscond: {
    type: "verb",
    meaning: "To leave hurriedly and secretly to avoid detection or arrest.",
    trick: "Think of 'absent' - to abscond is to make oneself absent.",
    synonyms: ["flee", "escape", "run away", "bolt"],
    examples: [
      "The thief absconded with the stolen goods.",
      "He absconded from the country to avoid prosecution.",
      "She absconded with the company's funds.",
      "The prisoner absconded from jail.",
      "They planned to abscond to a foreign country.",
    ],
  },
  abstruse: {
    type: "adjective",
    meaning: "Difficult to understand; obscure.",
    trick: "Think of 'abstract' - abstruse things are abstract and hard to understand.",
    synonyms: ["obscure", "arcane", "esoteric", "perplexing"],
    examples: [
      "His theories were too abstruse for the general public.",
      "The professor's lectures were abstruse.",
      "She struggled with the abstruse text.",
      "The concept was abstruse and required further explanation.",
      "The abstruse nature of the subject deterred many students.",
    ],
  },
  accolade: {
    type: "noun",
    meaning: "An award or privilege granted as a special honor or as an acknowledgment of merit.",
    trick: "Think of 'a cool aid' - an accolade is a cool aid or reward.",
    synonyms: ["honor", "award", "distinction", "praise"],
    examples: [
      "She received accolades for her performance.",
      "The scientist earned the highest accolade in her field.",
      "The actor's accolades included several awards.",
      "He received accolades for his charitable work.",
      "The team was given accolades for their success.",
    ],
  },
  acrimonious: {
    type: "adjective",
    meaning: "Typically of speech or a debate, angry and bitter.",
    trick: "Think of 'a criminal' - acrimonious debates can be as bitter as arguments with a criminal.",
    synonyms: ["bitter", "rancorous", "caustic", "acerbic"],
    examples: [
      "Their divorce was acrimonious.",
      "The discussion turned acrimonious.",
      "He made an acrimonious comment.",
      "The debate became increasingly acrimonious.",
      "They had an acrimonious dispute over money.",
    ],
  },
  adamant: {
    type: "adjective",
    meaning: "Refusing to be persuaded or to change one's mind.",
    trick: "Think of 'a dam' - adamant people are as unyielding as a dam.",
    synonyms: ["unyielding", "inflexible", "resolute", "stubborn"],
    examples: [
      "She was adamant about not going.",
      "He remained adamant in his decision.",
      "The company was adamant on their policy.",
      "Her parents were adamant that she finish her degree.",
      "He was adamant that he was right.",
    ],
  },
  admonish: {
    type: "verb",
    meaning: "To warn or reprimand someone firmly.",
    trick: "Think of 'add more' - admonish is to add more warning or reprimand.",
    synonyms: ["reprimand", "rebuke", "scold", "chide"],
    examples: [
      "She admonished him for being late.",
      "The teacher admonished the students for talking.",
      "He was admonished by his boss.",
      "She admonished the child for running into the street.",
      "The coach admonished the team for their poor performance.",
    ],
  },
  adroit: {
    type: "adjective",
    meaning: "Clever or skillful in using the hands or mind.",
    trick: "Think of 'a droid' - adroit people are as skillful as droids.",
    synonyms: ["skillful", "adept", "dexterous", "nimble"],
    examples: [
      "She is adroit at handling difficult situations.",
      "He gave an adroit performance.",
      "The carpenter's adroit hands worked quickly.",
      "Her adroit use of language impressed the audience.",
      "He was adroit in negotiating the deal.",
    ],
  },
  adulation: {
    type: "noun",
    meaning: "Excessive admiration or praise.",
    trick: "Think of 'adults' - adulation is the kind of praise adults might shower on someone.",
    synonyms: ["flattery", "praise", "admiration", "worship"],
    examples: [
      "The performer basked in the adulation of the crowd.",
      "She received adulation from her fans.",
      "His adulation of the celebrity was obvious.",
      "The adulation of the audience was overwhelming.",
      "She was embarrassed by the adulation she received.",
    ],
  },
  aesthetic: {
    type: "adjective",
    meaning: "Concerned with beauty or the appreciation of beauty.",
    trick: "Think of 'esthetician' - someone who works to enhance beauty.",
    synonyms: ["artistic", "tasteful", "elegant", "beautiful"],
    examples: [
      "The painting had great aesthetic appeal.",
      "She has a keen aesthetic sense.",
      "The building's aesthetic design was praised.",
      "He admired the aesthetic quality of the sculpture.",
      "The aesthetic value of the garden was undeniable.",
    ],
  },
  alacrity: {
    type: "noun",
    meaning: "Brisk and cheerful readiness.",
    trick: "Think of 'electricity' - someone with alacrity is as energetic as electricity.",
    synonyms: ["eagerness", "enthusiasm", "readiness", "willingness"],
    examples: [
      "She accepted the invitation with alacrity.",
      "He completed the task with alacrity.",
      "The volunteers worked with alacrity.",
      "They greeted the news with alacrity.",
      "Her alacrity to help was appreciated.",
    ],
  },
  alleviate: {
    type: "verb",
    meaning: "To make less severe.",
    trick: "Think of 'a leave' - alleviate means to leave some pain or stress.",
    synonyms: ["relieve", "ease", "reduce", "lessen"],
    examples: [
      "She took medication to alleviate the pain.",
      "The new policies aim to alleviate poverty.",
      "His speech helped alleviate their concerns.",
      "They donated money to alleviate suffering.",
      "The doctor prescribed a drug to alleviate the symptoms.",
    ],
  },
  ambivalent: {
    type: "adjective",
    meaning: "Having mixed feelings or contradictory ideas about something or someone.",
    trick: "Think of 'ambi' (both) - ambivalent people have feelings in both directions.",
    synonyms: ["uncertain", "unsure", "doubtful", "torn"],
    examples: [
      "She felt ambivalent about her new job.",
      "He was ambivalent about moving to a new city.",
      "The public has ambivalent feelings about the new policy.",
      "They were ambivalent regarding their decision.",
      "His ambivalent attitude confused his friends.",
    ],
  },
  ameliorate: {
    type: "verb",
    meaning: "To make something bad or unsatisfactory better.",
    trick: "Think of 'a meal' - ameliorate is like giving a meal to someone hungry to make things better.",
    synonyms: ["improve", "enhance", "better", "mitigate"],
    examples: [
      "The government aims to ameliorate living conditions.",
      "She worked hard to ameliorate the situation.",
      "New laws were introduced to ameliorate working conditions.",
      "His actions helped to ameliorate the crisis.",
      "They sought to ameliorate the effects of the disaster.",
    ],
  },
  amicable: {
    type: "adjective",
    meaning: "Having a spirit of friendliness; without serious disagreement.",
    trick: "Think of 'amigo' - amicable means friendly, like an amigo.",
    synonyms: ["friendly", "cordial", "harmonious", "peaceable"],
    examples: [
      "They reached an amicable agreement.",
      "The divorce was amicable.",
      "Their relationship remained amicable.",
      "They had an amicable conversation.",
      "The two countries maintained amicable relations.",
    ],
  },
  anachronism: {
    type: "noun",
    meaning: "A thing belonging to a period other than that in which it exists.",
    trick: "Think of 'chron' (time) - anachronism is something out of its proper time.",
    synonyms: ["misplacement", "prolepsis", "solecism", "chronological error"],
    examples: [
      "The film was full of anachronisms.",
      "His style of dress was an anachronism.",
      "The use of old technology is an anachronism.",
      "The story was ruined by anachronisms.",
      "He was considered an anachronism in the modern world.",
    ],
  },
  analogous: {
    type: "adjective",
    meaning: "Comparable in certain respects, typically in a way that makes clearer the nature of the things compared.",
    trick: "Think of 'analogy' - analogous things are comparable.",
    synonyms: ["comparable", "similar", "alike", "related"],
    examples: [
      "The wings of a bat and a bird are analogous.",
      "Her situation is analogous to his.",
      "They used an analogous example to explain the concept.",
      "The process is analogous to baking a cake.",
      "The two situations are not analogous.",
    ],
  },
  anomaly: {
    type: "noun",
    meaning: "Something that deviates from what is standard, normal, or expected.",
    trick: "Think of 'abnormality' - an anomaly is an abnormality.",
    synonyms: ["irregularity", "aberration", "deviation", "oddity"],
    examples: [
      "The test results showed an anomaly.",
      "There was an anomaly in the data.",
      "Her behavior was an anomaly.",
      "The discovery was considered an anomaly.",
      "The weather pattern is an anomaly.",
    ],
  },
  antipathy: {
    type: "noun",
    meaning: "A deep-seated feeling of dislike; aversion.",
    trick: "Think of 'anti-path' - antipathy means against or dislike.",
    synonyms: ["hostility", "aversion", "dislike", "enmity"],
    examples: [
      "She felt a strong antipathy towards her boss.",
      "His antipathy for the politician was evident.",
      "The two groups had a long history of antipathy.",
      "He expressed his antipathy in no uncertain terms.",
      "Their antipathy towards each other was obvious.",
    ],
  },
  apathy: {
    type: "noun",
    meaning: "Lack of interest, enthusiasm, or concern.",
    trick: "Think of 'a path' - someone with apathy doesn't follow any path with interest.",
    synonyms: ["indifference", "unconcern", "lethargy", "detachment"],
    examples: [
      "The campaign failed because of public apathy.",
      "She couldn't understand his apathy towards the issue.",
      "There was widespread apathy among the voters.",
      "His apathy was mistaken for laziness.",
      "The students' apathy was disheartening.",
    ],
  },
  apocryphal: {
    type: "adjective",
    meaning: "Of doubtful authenticity, although widely circulated as being true.",
    trick: "Think of 'crypt' - apocryphal stories are hidden and dubious.",
    synonyms: ["fictitious", "fabricated", "spurious", "doubtful"],
    examples: [
      "The story is probably apocryphal.",
      "He told an apocryphal tale of his adventures.",
      "The book contains many apocryphal anecdotes.",
      "The account of the event is apocryphal.",
      "The legend is largely apocryphal.",
    ],
  },
  appease: {
    type: "verb",
    meaning: "To pacify or placate someone by acceding to their demands.",
    trick: "Think of 'a peace' - to appease is to bring a peace.",
    synonyms: ["pacify", "placate", "mollify", "conciliate"],
    examples: [
      "They tried to appease the angry crowd.",
      "The policy was designed to appease the critics.",
      "She appeased her child with a promise of candy.",
      "He sought to appease his opponents.",
      "The company appeased its customers with refunds.",
    ],
  },
  approbation: {
    type: "noun",
    meaning: "Approval or praise.",
    trick: "Think of 'approve' - approbation means approval or praise.",
    synonyms: ["approval", "praise", "commendation", "endorsement"],
    examples: [
      "The plan received widespread approbation.",
      "She smiled with approbation.",
      "His work was met with approbation.",
      "The proposal won the approbation of the board.",
      "The artist sought approbation from his peers.",
    ],
  },
  arbitrary: {
    type: "adjective",
    meaning: "Based on random choice or personal whim, rather than any reason or system.",
    trick: "Think of 'a bit rare' - arbitrary decisions are rare and random.",
    synonyms: ["random", "capricious", "whimsical", "unpredictable"],
    examples: [
      "The decision was arbitrary.",
      "He made an arbitrary choice.",
      "The rules seemed arbitrary and unfair.",
      "The selection process was arbitrary.",
      "The arbitrary nature of the law was criticized.",
    ],
  },
  arcane: {
    type: "adjective",
    meaning: "Understood by few; mysterious or secret.",
    trick: "Think of 'a cane' - something arcane is as mysterious as a magic cane.",
    synonyms: ["mysterious", "secret", "esoteric", "enigmatic"],
    examples: [
      "The professor's lectures were arcane.",
      "The ritual was arcane and ancient.",
      "His knowledge of the subject was arcane.",
      "The book was full of arcane information.",
      "The language used was arcane and difficult to understand.",
    ],
  },
  arduous: {
    type: "adjective",
    meaning: "Involving or requiring strenuous effort; difficult and tiring.",
    trick: "Think of 'hard to do' - arduous tasks are hard to do.",
    synonyms: ["difficult", "strenuous", "laborious", "onerous"],
    examples: [
      "The journey was long and arduous.",
      "They faced an arduous climb up the mountain.",
      "The project proved to be more arduous than expected.",
      "He completed the arduous task with determination.",
      "Training for the marathon was an arduous process.",
    ],
  },
  belie: {
    type: "verb",
    meaning: "To give a false impression of; to contradict.",
    trick: "Think of 'be lie' - something that 'be' a 'lie' gives a false impression.",
    synonyms: ["contradict", "disprove", "negate", "confute"],
    examples: [
      "Her calm demeanor belied the panic she felt inside.",
      "The simplicity of the exam belied the difficulty of the questions.",
      "His cheerful smile belied his true feelings of sadness.",
      "The statistics belie the reality of the economic situation.",
      "Her appearance belied her age, making her look much younger.",
    ],
  },
  burnish: {
    type: "verb",
    meaning: "To polish (something, especially metal) by rubbing.",
    trick: "Think of 'burn' - burnish to make something shine as if burned.",
    synonyms: ["polish", "shine", "buff", "gloss"],
    examples: [
      "She used a cloth to burnish the silverware.",
      "The knight burnished his armor before the tournament.",
      "They burnished the floors until they gleamed.",
      "His reputation was burnished by the recent success.",
      "The car was burnished to a high shine.",
    ],
  },
  cacophony: {
    type: "noun",
    meaning: "A harsh, discordant mixture of sounds.",
    trick: "Think of 'caco' as bad and 'phony' as sound - bad sound.",
    synonyms: ["din", "racket", "noise", "clamor"],
    examples: [
      "The cacophony in the market was overwhelming.",
      "Her thoughts were drowned out by the cacophony of the city.",
      "The band produced a cacophony that hurt our ears.",
      "The room filled with the cacophony of shouting voices.",
      "The cacophony from the construction site was unbearable.",
    ],
  },
  capricious: {
    type: "adjective",
    meaning: "Given to sudden and unaccountable changes of mood or behavior.",
    trick: "Think of 'cap' - if you put a cap on your head, it changes your mood or behavior unexpectedly.",
    synonyms: ["fickle", "inconsistent", "volatile", "whimsical"],
    examples: [
      "The capricious weather ruined our picnic plans.",
      "Her capricious nature made it hard for her to keep long-term friends.",
      "Investors are wary of capricious markets.",
      "His capricious decision-making was frustrating for his team.",
      "The film's capricious plot kept the audience guessing.",
    ],
  },
  chicanery: {
    type: "noun",
    meaning: "The use of trickery to achieve a political, financial, or legal purpose.",
    trick: "Think of 'chickens' - chicanery involves tricking the chickens.",
    synonyms: ["deception", "trickery", "subterfuge", "fraud"],
    examples: [
      "The politician was accused of chicanery during the election.",
      "His chicanery in business dealings eventually caught up with him.",
      "The court case was filled with chicanery and lies.",
      "She used chicanery to get what she wanted.",
      "Their plan was full of chicanery and deceit.",
    ],
  },
  daunt: {
    type: "verb",
    meaning: "To make someone feel intimidated or apprehensive.",
    trick: "Think of 'haunt' - to daunt is to scare or intimidate.",
    synonyms: ["intimidate", "discourage", "deter", "frighten"],
    examples: [
      "The steep mountain did not daunt the climbers.",
      "She was daunted by the scale of the project.",
      "His confident demeanor daunted his opponents.",
      "The challenges ahead didn't daunt him.",
      "The idea of moving to a new city daunted her.",
    ],
  },
  desiccate: {
    type: "verb",
    meaning: "To remove the moisture from something, typically to preserve it.",
    trick: "Think of 'desert' - to desiccate is to make something dry like a desert.",
    synonyms: ["dry", "dehydrate", "parch", "wither"],
    examples: [
      "The hot sun desiccated the plants.",
      "They desiccate fruits to make snacks.",
      "The desiccated remains of the animals were found in the desert.",
      "Her desiccated skin needed moisturizing.",
      "The ancient manuscript was desiccated by time.",
    ],
  },
  ebullient: {
    type: "adjective",
    meaning: "Cheerful and full of energy.",
    trick: "Think of 'bull' - full of energy like a bull.",
    synonyms: ["exuberant", "enthusiastic", "animated", "vivacious"],
    examples: [
      "Her ebullient personality made her popular.",
      "The team was ebullient after their victory.",
      "He gave an ebullient speech that energized the crowd.",
      "The ebullient mood was infectious.",
      "Her ebullient nature was a source of joy for those around her.",
    ],
  },
  eclectic: {
    type: "adjective",
    meaning: "Deriving ideas, style, or taste from a broad and diverse range of sources.",
    trick: "Think of 'select' - someone who selects from various sources.",
    synonyms: ["diverse", "varied", "wide-ranging", "broad"],
    examples: [
      "Her eclectic taste in music includes everything from classical to hip hop.",
      "The restaurant's menu is eclectic, featuring dishes from around the world.",
      "His eclectic collection of art filled the room with color.",
      "The book club had an eclectic selection of genres.",
      "The architect's style was eclectic, combining modern and traditional elements.",
    ],
  },
  endeavour: {
    meaning: "To try hard to achieve something.",
    trick: "Endeavour sounds like 'end over', suggesting putting a lot of effort into reaching a goal.",
    synonyms: ["attempt", "strive", "undertake"],
    examples: [
      "She endeavored to learn a new language by practicing every day.",
      "Despite facing many obstacles, he endeavored to reach his goals.",
      "The company endeavored to provide better customer service.",
      "They endeavored to find a solution to the problem before it escalated.",
      "Endeavoring to find a cure, scientists conducted numerous experiments.",
    ],
  },
  endemic: {
    meaning: "Native or restricted to a certain place or region.",
    trick: "Endemic sounds like 'in-demic', indicating something specific to a particular demographic.",
    synonyms: ["indigenous", "native", "local"],
    examples: [
      "Malaria is endemic to tropical regions where the climate is suitable for mosquito breeding.",
      "The endangered species is endemic to this particular island and cannot be found anywhere else.",
      "Endemic corruption in the government has hindered the country's development.",
      "The plant species is endemic to the rainforest and cannot survive in other environments.",
      "The disease is endemic in certain parts of Africa, making it challenging to eradicate.",
    ],
  },
  endive: {
    meaning: "A leafy vegetable with a slightly bitter taste.",
    trick: "Endive sounds like 'endive', similar to how it's pronounced, aiding in easy recall.",
    synonyms: ["chicory", "escarole"],
    examples: [
      "She prepared a salad with fresh endive leaves and vinaigrette dressing.",
      "The dish featured roasted beets served with sliced endive.",
      "Endive is often used in gourmet salads for its unique flavor.",
      "He prefers to eat endive raw rather than cooked.",
      "The recipe called for endive as one of the main ingredients.",
    ],
  },
  endorse: {
    meaning: "To declare one's public approval or support of something.",
    trick: "Endorse sounds like 'in doors', implying public support or approval.",
    synonyms: ["approve", "support", "back"],
    examples: [
      "The celebrity endorsed the new perfume, leading to a surge in sales.",
      "The organization endorsed the candidate for their commitment to environmental issues.",
      "The company endorsed the charity event by donating a significant sum of money.",
      "He asked his friends to endorse his skills on his LinkedIn profile.",
      "The mayor publicly endorsed the plan to revitalize the city center.",
    ],
  },
  endue: {
    meaning: "To provide with a quality or ability.",
    trick: "Endue sounds like 'en + due', suggesting giving something its due quality or ability.",
    synonyms: ["endow", "grant", "bestow"],
    examples: [
      "The scholarship will endue her with the opportunity to pursue higher education.",
      "His parents endued him with a strong sense of responsibility from a young age.",
      "Education endues individuals with knowledge and skills necessary for success.",
      "The mentorship program aims to endue participants with leadership qualities.",
      "Their generosity endues the community with resources for growth and development.",
    ],
  },
  enervate: {
    meaning: "To weaken or drain of energy.",
    trick: "Enervate sounds like 'energy-vacate', suggesting draining energy.",
    synonyms: ["weaken", "debilitate", "exhaust"],
    examples: [
      "The intense heat enervated the hikers, causing fatigue and dehydration.",
      "The prolonged illness left him enervated, unable to perform daily tasks.",
      "The constant stress of work enervated her both physically and mentally.",
      "Lack of sleep can enervate the body and impair cognitive function.",
      "The long hours of studying enervated the students, leading to decreased productivity.",
    ],
  },
  engender: {
    meaning: "To cause or give rise to a feeling, situation, or condition.",
    trick: "Engender sounds like 'generate', implying creating or causing something.",
    synonyms: ["cause", "create", "produce"],
    examples: [
      "The divisive rhetoric engendered a sense of fear and distrust among the population.",
      "The economic policies are expected to engender widespread prosperity.",
      "His apology engendered forgiveness and reconciliation among family members.",
      "The project aims to engender a sense of community among residents.",
      "Their actions only served to engender further conflict and misunderstanding.",
    ],
  },
  enigma: {
    meaning: "A person or thing that is mysterious, puzzling, or difficult to understand.",
    trick: "Enigma sounds like 'inigma mystery', indicating something mysterious and difficult to comprehend.",
    synonyms: ["mystery", "puzzle", "riddle"],
    examples: [
      "The disappearance of the ancient artifact remains an enigma to historians.",
      "Her personality was an enigma, with layers of complexity that intrigued those around her.",
      "The true identity of the anonymous donor is an enigma to the charity organization.",
      "The strange lights in the sky were an enigma to the villagers.",
      "The coded message presented an enigma to the codebreakers.",
    ],
  },
  enjoin: {
    meaning: "To instruct or urge someone to do something.",
    trick: "Enjoin sounds like 'in join', suggesting joining in an action or instruction.",
    synonyms: ["urge", "command", "direct"],
    examples: [
      "The doctor enjoined her patient to rest and take the prescribed medication.",
      "It is the duty of parents to enjoin good behavior in their children.",
      "The judge enjoined the defendant to refrain from contacting the plaintiff.",
      "The teacher enjoined the students to complete their assignments on time.",
      "The coach enjoined the team to give their best effort in the upcoming match.",
    ],
  },
  ennui: {
    meaning: "A feeling of listlessness and dissatisfaction arising from a lack of occupation or excitement.",
    trick: "Ennui sounds like 'anew', but the feeling is quite the opposite; it's about boredom and dissatisfaction.",
    synonyms: ["boredom", "weariness", "tedium"],
    examples: [
      "The long summer afternoons often left him with a sense of ennui.",
      "She sought to alleviate her ennui by taking up new hobbies.",
      "The ennui of suburban life led him to contemplate moving to the city.",
      "The repetitive nature of the job filled him with ennui.",
      "He tried to shake off his ennui by immersing himself in books and music.",
    ],
  },
  enroute: {
    meaning: "During the course of a journey.",
    trick: "Enroute sounds like 'on route' - while on the way.",
    synonyms: ["on the way", "along the way", "in transit", "during the journey"],
    examples: [
      "We stopped for lunch enroute to the beach.",
      "He called me while enroute to the airport.",
      "They got lost enroute to the hotel.",
      "She read a book enroute to her destination.",
      "The package is enroute and will arrive tomorrow.",
    ],
  },
  ensconce: {
    meaning: "Establish or settle someone in a comfortable, safe, or secret place.",
    trick: "Ensconce sounds like 'in sconce' - to place snugly inside something.",
    synonyms: ["settle", "install", "nestle", "position"],
    examples: [
      "He ensconced himself in the armchair.",
      "The children were ensconced in their beds.",
      "She was comfortably ensconced in her new home.",
      "The spy was ensconced in a hidden location.",
      "They ensconced themselves in the cozy cabin.",
    ],
  },
  ensemble: {
    meaning: "A group of musicians, actors, or dancers who perform together.",
    trick: "Ensemble sounds like 'assemble' - a group assembled to perform.",
    synonyms: ["group", "band", "orchestra", "troupe"],
    examples: [
      "The ensemble performed beautifully.",
      "She joined a jazz ensemble.",
      "The play featured a talented ensemble cast.",
      "The ensemble practiced every day.",
      "An ensemble of musicians played at the event.",
    ],
  },
  entente: {
    meaning: "A friendly understanding or informal alliance between states or factions.",
    trick: "Entente sounds like 'intent' - intent on forming an agreement.",
    synonyms: ["agreement", "alliance", "understanding", "accord"],
    examples: [
      "The two countries formed an entente.",
      "They reached an entente on trade issues.",
      "The entente between the factions was fragile.",
      "An entente was established to maintain peace.",
      "The leaders signed an entente.",
    ],
  },
  enthrall: {
    meaning: "Capture the fascinated attention of.",
    trick: "Enthrall sounds like 'in thrall' - to be held captive by something amazing.",
    synonyms: ["captivate", "fascinate", "charm", "enchant"],
    examples: [
      "The magician's performance enthralled the audience.",
      "She was enthralled by the beautiful scenery.",
      "The book enthralled readers from start to finish.",
      "He was enthralled by her singing.",
      "The story enthralled everyone in the room.",
    ],
  },
  entice: {
    meaning: "Attract or tempt by offering pleasure or advantage.",
    trick: "Entice sounds like 'ent' + 'ice' - think of being lured by something cool.",
    synonyms: ["tempt", "lure", "attract", "allure"],
    examples: [
      "They used discounts to entice customers.",
      "The smell of food enticed him into the kitchen.",
      "Advertisements are designed to entice people to buy.",
      "The prospect of a bonus enticed employees to work harder.",
      "The bright lights enticed the moths.",
    ],
  },
  entity: {
    meaning: "A thing with distinct and independent existence.",
    trick: "Entity sounds like 'entirety' - something that exists as a whole.",
    synonyms: ["being", "creature", "organism", "individual"],
    examples: [
      "The company is a separate legal entity.",
      "Each department operates as an independent entity.",
      "The mind is a complex entity.",
      "A corporation is considered a single entity.",
      "The government recognized the new entity.",
    ],
  },
  entomology: {
    meaning: "The scientific study of insects.",
    trick: "Entomology sounds like 'insect' + 'ology' - the study of insects.",
    synonyms: ["insectology", "bug science"],
    examples: [
      "She studied entomology in college.",
      "Entomology involves the classification of insects.",
      "An entomology expert was called to identify the species.",
      "He published a paper on entomology.",
      "The entomology lab was filled with specimens.",
    ],
  },
  entourage: {
    meaning: "A group of people attending or surrounding an important person.",
    trick: "Entourage sounds like 'enter' + 'our' + 'age' - a group entering together.",
    synonyms: ["retinue", "escort", "followers", "staff"],
    examples: [
      "The celebrity arrived with an entourage.",
      "His entourage included bodyguards and assistants.",
      "The politician's entourage traveled with him.",
      "She was always surrounded by her entourage.",
      "The king's entourage followed him everywhere.",
    ],
  },
  entrance: {
    meaning: "An opening or passage through which one can enter.",
    trick: "Entrance sounds like 'enter' - the place where you enter.",
    synonyms: ["entry", "doorway", "gateway", "access"],
    examples: [
      "The entrance to the building was grand.",
      "He stood at the entrance, waiting for her.",
      "The main entrance is around the corner.",
      "They decorated the entrance for the event.",
      "Please use the side entrance.",
    ],
  },
  ephemeral: {
    type: "adjective",
    meaning: "Lasting for a very short time.",
    trick: "Think of 'e-femoral' - something ephemeral is as short-lived as an electronic pulse.",
    synonyms: ["short-lived", "transient", "fleeting", "momentary"],
    examples: [
      "The beauty of the sunset was ephemeral.",
      "Their joy was ephemeral, fading quickly.",
      "Fashion trends are often ephemeral.",
      "The ephemeral nature of fame can be disheartening.",
      "Spring flowers are ephemeral but beautiful.",
    ],
  },
  facetious: {
    type: "adjective",
    meaning: "Treating serious issues with deliberately inappropriate humor.",
    trick: "Think of 'face' - facetious people often have a funny face.",
    synonyms: ["flippant", "glib", "joking", "playful"],
    examples: [
      "His facetious remarks were not appreciated during the meeting.",
      "She made a facetious comment about the serious situation.",
      "The facetious tone of his voice indicated he was not being serious.",
      "Her facetious attitude was sometimes misunderstood.",
      "He was being facetious, not intending to offend anyone.",
    ],
  },
  fatuous: {
    type: "adjective",
    meaning: "Silly and pointless.",
    trick: "Think of 'fat' - a fatuous person might be full of hot air, making silly statements.",
    synonyms: ["silly", "foolish", "inane", "vapid"],
    examples: [
      "His fatuous remarks annoyed everyone.",
      "The conversation was filled with fatuous comments.",
      "She dismissed his fatuous suggestions.",
      "The movie was criticized for its fatuous plot.",
      "His fatuous grin irritated his colleagues.",
    ],
  },
  fervid: {
    type: "adjective",
    meaning: "Intensely enthusiastic or passionate, often to an excessive degree.",
    trick: "Think of 'fever' - a fervid person has a feverish passion.",
    synonyms: ["ardent", "passionate", "fervent", "enthusiastic"],
    examples: [
      "The speaker's fervid delivery captivated the audience.",
      "His fervid dedication to the cause inspired many.",
      "The fervid debate lasted well into the night.",
      "She wrote a fervid letter of protest.",
      "Their fervid support for the team was evident in their cheers.",
    ],
  },
  gainsay: {
    type: "verb",
    meaning: "To deny or contradict (a fact or statement).",
    trick: "Think of 'gain' and 'say' - you gain say by contradicting.",
    synonyms: ["deny", "dispute", "contradict", "refute"],
    examples: [
      "No one could gainsay the evidence.",
      "She was too honest to gainsay the truth.",
      "His reputation was such that no one dared to gainsay him.",
      "The witness gainsaid the prosecutor's assertions.",
      "He tried to gainsay the accusations against him.",
    ],
  },
  garrulous: {
    type: "adjective",
    meaning: "Excessively talkative, especially on trivial matters.",
    trick: "Think of 'garrulous' as 'garble' - talking too much can sound like garble.",
    synonyms: ["talkative", "loquacious", "verbose", "chatty"],
    examples: [
      "The garrulous old man bored everyone with his endless stories.",
      "Her garrulous nature made her the life of the party.",
      "The garrulous student was often scolded for talking in class.",
      "She found the garrulous neighbor quite annoying.",
      "His garrulous speech went on for hours.",
    ],
  },
  hackneyed: {
    type: "adjective",
    meaning: "Lacking significance through having been overused.",
    trick: "Think of 'hack' - something hackneyed is like a hack, overused and clichéd.",
    synonyms: ["overused", "clichéd", "trite", "banal"],
    examples: [
      "The movie's plot was hackneyed and predictable.",
      "He used hackneyed phrases in his speech.",
      "Her hackneyed excuses were no longer believed.",
      "The hackneyed joke failed to amuse the audience.",
      "The story's hackneyed theme bored the readers.",
    ],
  },
  harangue: {
    type: "noun",
    meaning: "A lengthy and aggressive speech.",
    trick: "Think of 'hurray' - but in a negative tone, like a long, aggressive cheer.",
    synonyms: ["tirade", "diatribe", "rant", "lecture"],
    examples: [
      "The politician's harangue lasted for hours.",
      "She delivered a harangue about the company's policies.",
      "His harangue against corruption was widely reported.",
      "The coach's harangue motivated the team.",
      "The harangue left the audience exhausted.",
    ],
  },
  iconoclast: {
    type: "noun",
    meaning: "A person who attacks or criticizes cherished beliefs or institutions.",
    trick: "Think of 'icon' and 'clash' - an iconoclast clashes with icons.",
    synonyms: ["critic", "rebel", "nonconformist", "heretic"],
    examples: [
      "The artist was known as an iconoclast in the art world.",
      "His iconoclastic views often led to heated debates.",
      "She was an iconoclast who challenged traditional gender roles.",
      "The iconoclast's writings were controversial.",
      "His iconoclast tendencies made him unpopular with the establishment.",
    ],
  },
  idiosyncrasy: {
    type: "noun",
    meaning: "A mode of behavior or way of thought peculiar to an individual.",
    trick: "Think of 'idiot' - someone with idiosyncrasies might seem odd like an idiot.",
    synonyms: ["peculiarity", "quirk", "eccentricity", "mannerism"],
    examples: [
      "His idiosyncrasies made him a unique character.",
      "She had an idiosyncrasy of twirling her hair when thinking.",
      "The idiosyncrasies of his speech were endearing.",
      "Each artist's idiosyncrasy is reflected in their work.",
      "His idiosyncrasy of wearing mismatched socks was well-known.",
    ],
  },
  impetuous: {
    type: "adjective",
    meaning: "Acting or done quickly and without thought or care.",
    trick: "Think of 'imp' - an impetuous imp acts without thinking.",
    synonyms: ["rash", "impulsive", "hasty", "reckless"],
    examples: [
      "His impetuous decision to quit his job shocked everyone.",
      "The impetuous child often got into trouble.",
      "Her impetuous actions led to unintended consequences.",
      "He regretted his impetuous purchase.",
      "The impetuous nature of youth can be both a strength and a weakness.",
    ],
  },
  jettison: {
    type: "verb",
    meaning: "To throw or drop something from an aircraft or ship.",
    trick: "Think of 'jet' - to jettison is to throw out from a jet.",
    synonyms: ["discard", "dump", "abandon", "eject"],
    examples: [
      "The crew had to jettison the cargo to lighten the load.",
      "They jettisoned old equipment to make room for new supplies.",
      "He decided to jettison his outdated beliefs.",
      "The company jettisoned its unprofitable divisions.",
      "She jettisoned her worries and enjoyed the vacation.",
    ],
  },
  jubilant: {
    type: "adjective",
    meaning: "Feeling or expressing great happiness and triumph.",
    trick: "Think of 'jubilee' - a jubilant celebration.",
    synonyms: ["joyful", "elated", "triumphant", "exuberant"],
    examples: [
      "The fans were jubilant after their team won the championship.",
      "She felt jubilant when she received the job offer.",
      "The jubilant crowd celebrated in the streets.",
      "Their jubilant laughter filled the room.",
      "The mood was jubilant at the graduation ceremony.",
    ],
  },
  juxtapose: {
    type: "verb",
    meaning: "To place or deal with close together for contrasting effect.",
    trick: "Think of 'juxta' as 'next to' - juxtapose is to place next to.",
    synonyms: ["compare", "contrast", "collocate", "pair"],
    examples: [
      "The artist juxtaposed light and dark colors.",
      "The report juxtaposed the benefits and drawbacks of the policy.",
      "Juxtaposing the two theories highlighted their differences.",
      "The film juxtaposed scenes of war and peace.",
      "He juxtaposed his quiet demeanor with his loud outfit.",
    ],
  },
  kinetic: {
    type: "adjective",
    meaning: "Relating to or resulting from motion.",
    trick: "Think of 'kinetic energy' - energy from motion.",
    synonyms: ["active", "dynamic", "lively", "moving"],
    examples: [
      "The kinetic energy of the moving car was impressive.",
      "His kinetic performance energized the audience.",
      "The kinetic sculpture moved with the wind.",
      "Her kinetic approach to teaching kept students engaged.",
      "The city's kinetic atmosphere was exhilarating.",
    ],
  },
  knell: {
    type: "noun",
    meaning: "The sound of a bell, especially when rung solemnly for a death or funeral.",
    trick: "Think of 'knell' as 'nail' - the knell is like the final nail in a coffin.",
    synonyms: ["toll", "ring", "chime", "peal"],
    examples: [
      "The knell of the church bell signaled the funeral's start.",
      "The knell rang out across the village.",
      "The somber knell filled the air with melancholy.",
      "The knell was a reminder of mortality.",
      "The knell echoed through the valley.",
    ],
  },
  laconic: {
    type: "adjective",
    meaning: "Using very few words.",
    trick: "Think of 'lack' - someone laconic lacks words.",
    synonyms: ["terse", "succinct", "concise", "brief"],
    examples: [
      "His laconic reply suggested he was not interested.",
      "The manager's laconic speech left much to be desired.",
      "She admired his laconic style of writing.",
      "The witness was surprisingly laconic during the testimony.",
      "His laconic responses frustrated the interviewer.",
    ],
  },
  languid: {
    type: "adjective",
    meaning: "Lacking in energy or vitality; sluggish.",
    trick: "Think of 'languish' - to languid is to feel weak and listless.",
    synonyms: ["lethargic", "listless", "sluggish", "lazy"],
    examples: [
      "The hot weather made everyone feel languid.",
      "She moved with a languid grace.",
      "His languid response indicated disinterest.",
      "The languid afternoon passed slowly.",
      "They spent a languid day at the beach.",
    ],
  },
  magnanimous: {
    type: "adjective",
    meaning: "Very generous or forgiving, especially toward a rival or someone less powerful.",
    trick: "Think of 'magnify' - magnanimous people have big hearts.",
    synonyms: ["generous", "forgiving", "charitable", "benevolent"],
    examples: [
      "He was magnanimous in victory.",
      "She showed a magnanimous spirit towards her competitors.",
      "The magnanimous gesture was appreciated by all.",
      "They praised his magnanimous nature.",
      "Her magnanimous attitude won her many friends.",
    ],
  },
  mendacious: {
    type: "adjective",
    meaning: "Not telling the truth; lying.",
    trick: "Think of 'mend a lie' - a mendacious person mends lies.",
    synonyms: ["dishonest", "deceitful", "untruthful", "lying"],
    examples: [
      "The politician's mendacious statements were exposed by the press.",
      "Her mendacious behavior lost her many friends.",
      "He was known for his mendacious nature.",
      "The witness gave a mendacious testimony.",
      "She couldn't trust his mendacious words.",
    ],
  },
  mollify: {
    type: "verb",
    meaning: "To appease the anger or anxiety of someone.",
    trick: "Think of 'melt' - to mollify is to melt away anger.",
    synonyms: ["appease", "pacify", "soothe", "calm"],
    examples: [
      "She tried to mollify the angry customer.",
      "His apology mollified her feelings.",
      "The government took steps to mollify public opinion.",
      "They worked to mollify tensions between the two groups.",
      "Her kind words helped mollify his anger.",
    ],
  },
  nefarious: {
    type: "adjective",
    meaning: "Wicked or criminal.",
    trick: "Think of 'nefarious' as 'notorious' - nefarious people are notorious for being evil.",
    synonyms: ["wicked", "evil", "sinister", "villainous"],
    examples: [
      "The nefarious plot was uncovered by the police.",
      "He was known for his nefarious activities.",
      "The villain's nefarious deeds were finally exposed.",
      "They engaged in nefarious schemes.",
      "The nefarious criminal was brought to justice.",
    ],
  },
  neophyte: {
    type: "noun",
    meaning: "A person who is new to a subject, skill, or belief.",
    trick: "Think of 'neo' meaning new - a neophyte is new to something.",
    synonyms: ["beginner", "novice", "rookie", "amateur"],
    examples: [
      "The neophyte struggled to learn the ropes.",
      "As a neophyte, he needed a lot of guidance.",
      "The class is designed for neophytes in the field.",
      "Her neophyte enthusiasm was refreshing.",
      "The neophyte's questions were basic but important.",
    ],
  },
  obdurate: {
    type: "adjective",
    meaning: "Stubbornly refusing to change one's opinion or course of action.",
    trick: "Think of 'obstacle' - an obdurate person is an obstacle to change.",
    synonyms: ["stubborn", "inflexible", "unyielding", "adamant"],
    examples: [
      "His obdurate refusal to listen frustrated his colleagues.",
      "The obdurate stance of the leader led to a deadlock.",
      "She remained obdurate despite their pleas.",
      "The obdurate attitude of the team hindered progress.",
      "He was known for his obdurate determination.",
    ],
  },
  obfuscate: {
    type: "verb",
    meaning: "To render obscure, unclear, or unintelligible.",
    trick: "Think of 'obscure' - to obfuscate is to make something obscure.",
    synonyms: ["confuse", "obscure", "bewilder", "muddle"],
    examples: [
      "The politician tried to obfuscate the issue.",
      "His explanation only served to obfuscate matters.",
      "She used jargon to obfuscate her real intentions.",
      "The instructions were obfuscated by technical terms.",
      "He obfuscated the truth with lies.",
    ],
  },
  palpable: {
    type: "adjective",
    meaning: "So intense as to be almost touched or felt; clear to the mind or plain to see.",
    trick: "Think of 'palp' - something palpable can be palpated (felt).",
    synonyms: ["tangible", "perceptible", "noticeable", "obvious"],
    examples: [
      "The tension in the room was palpable.",
      "There was a palpable sense of relief.",
      "The excitement of the crowd was palpable.",
      "His disappointment was palpable.",
      "The fear in her voice was palpable.",
    ],
  },
  panacea: {
    type: "noun",
    meaning: "A solution or remedy for all difficulties or diseases.",
    trick: "Think of 'pan' (all) - a panacea is a cure for all.",
    synonyms: ["cure-all", "universal remedy", "elixir", "magic bullet"],
    examples: [
      "They hoped the new policy would be a panacea for the economic problems.",
      "There is no panacea for the challenges we face.",
      "The panacea he proposed was too simplistic.",
      "Some people believe that education is a panacea for all societal issues.",
      "The scientist searched for a panacea to cure the disease.",
    ],
  },
  paragon: {
    type: "noun",
    meaning: "A model of excellence or perfection.",
    trick: "Think of 'paradigm' - a paragon is a perfect example.",
    synonyms: ["exemplar", "ideal", "model", "quintessence"],
    examples: [
      "She is a paragon of virtue.",
      "The CEO was considered a paragon of leadership.",
      "Their performance was a paragon of teamwork.",
      "The artist's work is often viewed as a paragon of creativity.",
      "He is a paragon of what a student-athlete should be.",
    ],
  },
  quandary: {
    type: "noun",
    meaning: "A state of perplexity or uncertainty over what to do in a difficult situation.",
    trick: "Think of 'quandary' as a question mark in a diary - a state of uncertainty.",
    synonyms: ["dilemma", "predicament", "plight", "confusion"],
    examples: [
      "She was in a quandary about whether to accept the job offer.",
      "His quandary was whether to stay or leave.",
      "The decision left him in a quandary.",
      "They faced a quandary over how to handle the situation.",
      "The company was in a quandary about how to proceed.",
    ],
  },
  quixotic: {
    type: "adjective",
    meaning: "Exceedingly idealistic; unrealistic and impractical.",
    trick: "Think of 'Don Quixote' - quixotic people have unrealistic dreams like Don Quixote.",
    synonyms: ["idealistic", "impractical", "unrealistic", "romantic"],
    examples: [
      "His quixotic plans were never realized.",
      "She had a quixotic dream of world peace.",
      "The quixotic project failed due to lack of funding.",
      "His quixotic nature made him a dreamer.",
      "The proposal was dismissed as quixotic.",
    ],
  },
  rancor: {
    type: "noun",
    meaning: "Bitterness or resentfulness, especially when long-standing.",
    trick: "Think of 'rank' - rancor is like a rank, bitter feeling.",
    synonyms: ["bitterness", "resentment", "animosity", "enmity"],
    examples: [
      "The rancor between the two families was palpable.",
      "He spoke with rancor about his former boss.",
      "The debate was filled with rancor.",
      "There was no rancor in her voice despite the disagreement.",
      "Years of rancor had soured their relationship.",
    ],
  },
  recalcitrant: {
    type: "adjective",
    meaning: "Having an obstinately uncooperative attitude toward authority or discipline.",
    trick: "Think of 'recalcitrant' as 'rebel' - recalcitrant people are rebellious.",
    synonyms: ["uncooperative", "defiant", "rebellious", "obstinate"],
    examples: [
      "The recalcitrant student refused to follow the rules.",
      "He was known for his recalcitrant behavior.",
      "The recalcitrant employees were disciplined.",
      "Her recalcitrant attitude made it difficult to work with her.",
      "They faced a recalcitrant population resistant to change.",
    ],
  },
  rescind: {
    type: "verb",
    meaning: "To revoke, cancel, or repeal (a law, order, or agreement).",
    trick: "Think of 're-send' - to rescind is to send back or cancel.",
    synonyms: ["revoke", "repeal", "annul", "nullify"],
    examples: [
      "The government decided to rescind the controversial law.",
      "They had to rescind the invitation due to unforeseen circumstances.",
      "The company rescinded the job offer after discovering discrepancies in his resume.",
      "The policy was rescinded after public outcry.",
      "The board voted to rescind the previous decision.",
    ],
  },
  sagacious: {
    type: "adjective",
    meaning: "Having or showing keen mental discernment and good judgment.",
    trick: "Think of 'sage' - a sagacious person is like a wise sage.",
    synonyms: ["wise", "shrewd", "astute", "prudent"],
    examples: [
      "The sagacious leader made a wise decision.",
      "Her sagacious advice was invaluable.",
      "He was known for his sagacious judgment.",
      "The sagacious investor avoided the risky venture.",
      "They followed his sagacious guidance.",
    ],
  },
  salient: {
    type: "adjective",
    meaning: "Most noticeable or important.",
    trick: "Think of 'sail' - something salient stands out like a sail on a boat.",
    synonyms: ["prominent", "notable", "conspicuous", "striking"],
    examples: [
      "The salient points of the speech were well-received.",
      "Her most salient feature was her bright red hair.",
      "The report highlighted the salient issues.",
      "His salient achievements were recognized by all.",
      "The salient facts of the case were presented to the jury.",
    ],
  },
  tantamount: {
    type: "adjective",
    meaning: "Equivalent in seriousness to; virtually the same as.",
    trick: "Think of 'tangible amount' - something tantamount is virtually the same as something else.",
    synonyms: ["equivalent", "equal", "synonymous", "comparable"],
    examples: [
      "His resignation was tantamount to an admission of guilt.",
      "Refusing to help was tantamount to betrayal.",
      "Her silence was tantamount to agreement.",
      "The threat was tantamount to a declaration of war.",
      "The company's failure to act was tantamount to negligence.",
    ],
  },
  ubiquitous: {
    type: "adjective",
    meaning: "Present, appearing, or found everywhere.",
    trick: "Think of 'you be everywhere' - something ubiquitous is everywhere.",
    synonyms: ["omnipresent", "everywhere", "pervasive", "universal"],
    examples: [
      "Smartphones have become ubiquitous in modern society.",
      "The politician's ubiquitous presence was hard to ignore.",
      "Fast food chains are ubiquitous around the world.",
      "His ubiquitous influence was felt in every department.",
      "The brand's logo was ubiquitous, seen on every street corner.",
    ],
  },
  venerate: {
    type: "verb",
    meaning: "To regard with great respect; revere.",
    trick: "Think of 'veteran' - you venerate a veteran with respect.",
    synonyms: ["revere", "respect", "admire", "honor"],
    examples: [
      "The community venerated the old man for his wisdom.",
      "They venerate their ancestors during the festival.",
      "She was venerated for her philanthropic work.",
      "The professor was venerated by students and colleagues alike.",
      "The shrine is venerated as a sacred place.",
    ],
  },
  vex: {
    type: "verb",
    meaning: "To make someone feel annoyed, frustrated, or worried.",
    trick: "Think of 'vexed' - a vexed person is annoyed or frustrated.",
    synonyms: ["annoy", "irritate", "frustrate", "exasperate"],
    examples: [
      "The constant delays began to vex the commuters.",
      "His contradictory statements vexed the audience.",
      "The unresolved issue continued to vex her.",
      "She was vexed by his rude behavior.",
      "The problem vexed the engineers for weeks.",
    ],
  },
  wary: {
    type: "adjective",
    meaning: "Feeling or showing caution about possible dangers or problems.",
    trick: "Think of 'worry' - a wary person is cautious and worried about potential dangers.",
    synonyms: ["cautious", "alert", "vigilant", "circumspect"],
    examples: [
      "The hikers were wary of the potential for bear encounters.",
      "Investors are wary of the volatile market.",
      "She gave him a wary look, unsure of his intentions.",
      "He was wary of making any commitments.",
      "The wary cat approached the new toy slowly.",
    ],
  },
  whimsical: {
    type: "adjective",
    meaning: "Playfully quaint or fanciful, especially in an appealing and amusing way.",
    trick: "Think of 'whim' - whimsical things come from whims.",
    synonyms: ["fanciful", "playful", "quaint", "amusing"],
    examples: [
      "The whimsical illustrations delighted children.",
      "Her whimsical sense of humor made her popular.",
      "The film had a whimsical charm.",
      "He had a whimsical approach to life.",
      "The garden was decorated with whimsical sculptures.",
    ],
  },
  xenophobia: {
    type: "noun",
    meaning: "Dislike of or prejudice against people from other countries.",
    trick: "Think of 'xeno' meaning foreign and 'phobia' meaning fear.",
    synonyms: ["bigotry", "prejudice", "racism", "nationalism"],
    examples: [
      "The rise in xenophobia has been concerning.",
      "Her xenophobia made it difficult for her to accept new neighbors.",
      "The government's policies were criticized for promoting xenophobia.",
      "Efforts to combat xenophobia are increasing globally.",
      "Xenophobia can lead to social and economic isolation.",
    ],
  },
  yoke: {
    type: "noun",
    meaning:
      "A wooden crosspiece that is fastened over the necks of two animals and attached to the plow or cart that they are to pull; a symbol of burden or oppression.",
    trick: "Think of 'yolk' - a yolk is something that holds things together, like a yoke holds animals together.",
    synonyms: ["burden", "bondage", "oppression", "enslavement"],
    examples: [
      "The yoke of colonial rule was finally lifted.",
      "They struggled to break free from the yoke of oppression.",
      "The yoke of tradition was heavy on the young couple.",
      "She felt the yoke of responsibility weighing on her shoulders.",
      "The yoke was a symbol of the farmers' hard labor.",
    ],
  },
  zeal: {
    type: "noun",
    meaning: "Great energy or enthusiasm in pursuit of a cause or objective.",
    trick: "Think of 'zealous' - someone with zeal is zealous.",
    synonyms: ["enthusiasm", "passion", "ardor", "fervor"],
    examples: [
      "His zeal for the project was contagious.",
      "She approached the task with great zeal.",
      "The volunteers worked with zeal to help the victims.",
      "His religious zeal was evident in his sermons.",
      "The team's zeal for victory drove them to train harder.",
    ],
  },
};
